name: devine
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  audioplayers: ^6.0.0
  http: ^0.13.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/france.png
    - assets/images/allemagne.png
    - assets/images/argentine.png
    - assets/images/brazil.png
    - assets/images/canada.png
    - assets/images/chine.png
    - assets/images/egypte.png
    - assets/images/englais.png
    - assets/images/espagne.png
    - assets/images/inde.png
    - assets/images/italie.png
    - assets/images/japon.png
    - assets/images/portugal.png
    - assets/images/russie.png
    - assets/images/usa.png
    - assets/images/facile1.png
    - assets/images/medium.png
    - assets/images/difficile.png
    - assets/images/logo.png
    - assets/images/albert.png
    - assets/images/voiture.png
    - assets/images/avion.png
    - assets/images/moto.png
    - assets/images/train.png
    - assets/images/sn4.png
    - assets/images/sn3.png
    - assets/images/sn2.png
    - assets/images/sn1.png
    - assets/images/py4.png
    - assets/images/py3.png
    - assets/images/py2.png
    - assets/images/py1.png
    - assets/images/bolt.png
    - assets/images/castro.png
    - assets/images/clinton.png
    - assets/images/davinci.png
    - assets/images/degaulle.png
    - assets/images/ford.png
    - assets/images/mandela.png
    - assets/images/margaret.png
    - assets/images/marie.png
    - assets/images/marley.png
    - assets/images/martin.png
    - assets/images/putin.png
    - assets/images/rowling.png
    - assets/images/vangogh.png
    - assets/images/backqui.png
    - assets/images/backana.png
    - assets/images/backanag.png
    - assets/images/backima.png
    - assets/images/backsuis.png
    - assets/images/backpays.png
    - assets/images/backyyy.png
    - assets/images/backcalculs.png
    - assets/images/blackcalcul.png
    - assets/images/backpayss.png
    - assets/images/backmot.png
    - assets/images/backmott.png
    - assets/images/pe1.png
    - assets/images/pe2.png
    - assets/images/pe3.png
    - assets/images/pe4.png
    - assets/images/amsterdam.png
    - assets/images/ankara.png
    - assets/images/arabie.png
    - assets/images/argentine.png
    - assets/images/astana.png
    - assets/images/athene.png
    - assets/images/australie.png
    - assets/images/bangkok.png
    - assets/images/belgique.png
    - assets/images/berne.png
    - assets/images/bich.png
    - assets/images/bolivie.png
    - assets/images/bostwana.png
    - assets/images/budapest.png
    - assets/images/conakry.png
    - assets/images/copen.png
    - assets/images/dou.png
    - assets/images/dublin.png
    - assets/images/gua.png
    - assets/images/hels.png
    - assets/images/inde.png
    - assets/images/kampala.png
    - assets/images/mada.png
    - assets/images/mongolie.png
    - assets/images/oslo.png
    - assets/images/para.png
    - assets/images/portugal.png
    - assets/images/seoul.png
    - assets/images/sto.png
    - assets/images/teheran.png
    - assets/images/varsovie.png
    - assets/images/haskell.png
    - assets/images/html.png
    - assets/images/java.png
    - assets/images/javascript.png
    - assets/images/prolog.png
    - assets/images/python.png
    - assets/images/ruby.png
    - assets/images/scala.png
    - assets/images/sql.png
    - assets/images/go.png
    - assets/images/css.png
    - assets/images/cplus.png
    - assets/images/c.png
    - assets/images/ananas.png
    - assets/images/aubergine.png
    - assets/images/avocat.png
    - assets/images/banane.png
    - assets/images/blue.png
    - assets/images/brocoli.png
    - assets/images/carotte.png
    - assets/images/fraise.png
    - assets/images/laitue.png
    - assets/images/lemon.png
    - assets/images/orange.png
    - assets/images/pasteque.png
    - assets/images/pomme.png
    - assets/images/tomate.png
    - assets/images/abd.png
    - assets/images/alaphasy.png
    - assets/images/babacar.png
    - assets/images/bamba.png
    - assets/images/bastia.png
    - assets/images/billgates.png
    - assets/images/blaise.png
    - assets/images/blue.png
    - assets/images/graham.png
    - assets/images/jordan.png
    - assets/images/juliaroberts.png
    - assets/images/larry.png
    - assets/images/mamadoudia.png
    - assets/images/mandela.png
    - assets/images/meghan.png
    - assets/images/mjordan.png
    - assets/images/nader.png
    - assets/images/ro.png
    - assets/images/sedar.png
    - assets/images/sudais.png
    - assets/images/valdiodio.png
    - assets/images/videos/video.mp4
    - assets/images/greenn.png
    - assets/images/qui.png
    - assets/images/square.png
    - assets/images/dubai.png
    - assets/images/medine.png
    - assets/images/haram.png
    - assets/images/tour.png
    - assets/images/elisee.png
    - assets/images/aire.png
    - assets/images/soufflle.png
    - assets/images/quinzee.png
    - assets/images/dixe.png
    - assets/images/horizon.png
    - assets/images/ombre.png
    - assets/images/brend.png
    - assets/images/brenda.png
    - assets/images/colisee.png
    - assets/images/colise.png
    - assets/images/mahal.png
    - assets/images/mumbai.png
    - assets/images/murail.png
    - assets/images/muraille.png
    - assets/images/parte.png
    - assets/images/part.png
    - assets/images/phpp.png
    - assets/images/php.png
    - assets/images/statute.png
    - assets/images/statut.png
    - assets/images/tour.png
    - assets/images/pinke.png
    - assets/images/day.png
    - assets/images/anna.png
    - assets/images/annan.png
    - assets/images/A.png
    - assets/images/hu.png
    - assets/images/lola.png
    - assets/images/simple.png
    - assets/sounds/son1.mp3
    - assets/images/jiji.png
    - assets/images/rose.png
